-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject is
port (
    input_1_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    layer8_out_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    w2_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    w2_EN_A : OUT STD_LOGIC;
    w2_Din_A : OUT STD_LOGIC_VECTOR (15 downto 0);
    w2_Dout_A : IN STD_LOGIC_VECTOR (15 downto 0);
    w2_WEN_A : OUT STD_LOGIC_VECTOR (1 downto 0);
    w2_Clk_A : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    w2_Rst_A : OUT STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    w2_Addr_B : OUT STD_LOGIC_VECTOR (31 downto 0);
    w2_EN_B : OUT STD_LOGIC;
    w2_Din_B : OUT STD_LOGIC_VECTOR (15 downto 0);
    w2_Dout_B : IN STD_LOGIC_VECTOR (15 downto 0);
    w2_WEN_B : OUT STD_LOGIC_VECTOR (1 downto 0);
    w2_Clk_B : OUT STD_LOGIC;
    w2_Rst_B : OUT STD_LOGIC;
    b2_0 : IN STD_LOGIC_VECTOR (15 downto 0);
    b2_1 : IN STD_LOGIC_VECTOR (15 downto 0);
    b2_2 : IN STD_LOGIC_VECTOR (15 downto 0);
    b2_3 : IN STD_LOGIC_VECTOR (15 downto 0);
    b2_4 : IN STD_LOGIC_VECTOR (15 downto 0);
    b2_5 : IN STD_LOGIC_VECTOR (15 downto 0);
    b2_6 : IN STD_LOGIC_VECTOR (15 downto 0);
    b2_7 : IN STD_LOGIC_VECTOR (15 downto 0);
    b2_8 : IN STD_LOGIC_VECTOR (15 downto 0);
    b2_9 : IN STD_LOGIC_VECTOR (15 downto 0);
    b2_10 : IN STD_LOGIC_VECTOR (15 downto 0);
    b2_11 : IN STD_LOGIC_VECTOR (15 downto 0);
    b2_12 : IN STD_LOGIC_VECTOR (15 downto 0);
    b2_13 : IN STD_LOGIC_VECTOR (15 downto 0);
    b2_14 : IN STD_LOGIC_VECTOR (15 downto 0);
    b2_15 : IN STD_LOGIC_VECTOR (15 downto 0);
    b2_16 : IN STD_LOGIC_VECTOR (15 downto 0);
    b2_17 : IN STD_LOGIC_VECTOR (15 downto 0);
    b2_18 : IN STD_LOGIC_VECTOR (15 downto 0);
    b2_19 : IN STD_LOGIC_VECTOR (15 downto 0);
    w4_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    w4_EN_A : OUT STD_LOGIC;
    w4_Din_A : OUT STD_LOGIC_VECTOR (15 downto 0);
    w4_Dout_A : IN STD_LOGIC_VECTOR (15 downto 0);
    w4_WEN_A : OUT STD_LOGIC_VECTOR (1 downto 0);
    w4_Clk_A : OUT STD_LOGIC;
    w4_Rst_A : OUT STD_LOGIC;
    w4_Addr_B : OUT STD_LOGIC_VECTOR (31 downto 0);
    w4_EN_B : OUT STD_LOGIC;
    w4_Din_B : OUT STD_LOGIC_VECTOR (15 downto 0);
    w4_Dout_B : IN STD_LOGIC_VECTOR (15 downto 0);
    w4_WEN_B : OUT STD_LOGIC_VECTOR (1 downto 0);
    w4_Clk_B : OUT STD_LOGIC;
    w4_Rst_B : OUT STD_LOGIC;
    b4_0 : IN STD_LOGIC_VECTOR (15 downto 0);
    b4_1 : IN STD_LOGIC_VECTOR (15 downto 0);
    b4_2 : IN STD_LOGIC_VECTOR (15 downto 0);
    b4_3 : IN STD_LOGIC_VECTOR (15 downto 0);
    b4_4 : IN STD_LOGIC_VECTOR (15 downto 0);
    b4_5 : IN STD_LOGIC_VECTOR (15 downto 0);
    b4_6 : IN STD_LOGIC_VECTOR (15 downto 0);
    b4_7 : IN STD_LOGIC_VECTOR (15 downto 0);
    b4_8 : IN STD_LOGIC_VECTOR (15 downto 0);
    b4_9 : IN STD_LOGIC_VECTOR (15 downto 0);
    w7_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    w7_EN_A : OUT STD_LOGIC;
    w7_Din_A : OUT STD_LOGIC_VECTOR (15 downto 0);
    w7_Dout_A : IN STD_LOGIC_VECTOR (15 downto 0);
    w7_WEN_A : OUT STD_LOGIC_VECTOR (1 downto 0);
    w7_Clk_A : OUT STD_LOGIC;
    w7_Rst_A : OUT STD_LOGIC;
    w7_Addr_B : OUT STD_LOGIC_VECTOR (31 downto 0);
    w7_EN_B : OUT STD_LOGIC;
    w7_Din_B : OUT STD_LOGIC_VECTOR (15 downto 0);
    w7_Dout_B : IN STD_LOGIC_VECTOR (15 downto 0);
    w7_WEN_B : OUT STD_LOGIC_VECTOR (1 downto 0);
    w7_Clk_B : OUT STD_LOGIC;
    w7_Rst_B : OUT STD_LOGIC;
    input_1_TVALID : IN STD_LOGIC;
    input_1_TREADY : OUT STD_LOGIC;
    ap_start : IN STD_LOGIC;
    layer8_out_TVALID : OUT STD_LOGIC;
    layer8_out_TREADY : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC );
end;


architecture behav of myproject is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "myproject_myproject,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcku5p-ffvb676-2-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=4.304000,HLS_SYN_LAT=416350,HLS_SYN_TPT=141314,HLS_SYN_MEM=55,HLS_SYN_DSP=0,HLS_SYN_FF=125441,HLS_SYN_LUT=141551,HLS_VERSION=2023_2}";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_rst_n_inv : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_start : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_done : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_continue : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_idle : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_ready : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_start_out : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_start_write : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_input_1_TREADY : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_layer2_out_din : STD_LOGIC_VECTOR (319 downto 0);
    signal conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_layer2_out_write : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_w2_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_w2_EN_A : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_w2_WEN_A : STD_LOGIC_VECTOR (1 downto 0);
    signal conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_w2_Din_A : STD_LOGIC_VECTOR (15 downto 0);
    signal conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_w2_Addr_B : STD_LOGIC_VECTOR (31 downto 0);
    signal conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_w2_EN_B : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_w2_WEN_B : STD_LOGIC_VECTOR (1 downto 0);
    signal conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_w2_Din_B : STD_LOGIC_VECTOR (15 downto 0);
    signal relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_start : STD_LOGIC;
    signal relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_done : STD_LOGIC;
    signal relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_continue : STD_LOGIC;
    signal relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_idle : STD_LOGIC;
    signal relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_ready : STD_LOGIC;
    signal relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_layer2_out_read : STD_LOGIC;
    signal relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_layer3_out_din : STD_LOGIC_VECTOR (319 downto 0);
    signal relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_layer3_out_write : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_start : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_done : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_continue : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_idle : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_ready : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_start_out : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_start_write : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_layer3_out_read : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_layer4_out_din : STD_LOGIC_VECTOR (159 downto 0);
    signal conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_layer4_out_write : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_w4_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_w4_EN_A : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_w4_WEN_A : STD_LOGIC_VECTOR (1 downto 0);
    signal conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_w4_Din_A : STD_LOGIC_VECTOR (15 downto 0);
    signal conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_w4_Addr_B : STD_LOGIC_VECTOR (31 downto 0);
    signal conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_w4_EN_B : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_w4_WEN_B : STD_LOGIC_VECTOR (1 downto 0);
    signal conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_w4_Din_B : STD_LOGIC_VECTOR (15 downto 0);
    signal relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_start : STD_LOGIC;
    signal relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_done : STD_LOGIC;
    signal relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_continue : STD_LOGIC;
    signal relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_idle : STD_LOGIC;
    signal relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_ready : STD_LOGIC;
    signal relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_layer4_out_read : STD_LOGIC;
    signal relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_layer5_out_din : STD_LOGIC_VECTOR (159 downto 0);
    signal relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_layer5_out_write : STD_LOGIC;
    signal dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_start : STD_LOGIC;
    signal dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_done : STD_LOGIC;
    signal dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_continue : STD_LOGIC;
    signal dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_idle : STD_LOGIC;
    signal dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_ready : STD_LOGIC;
    signal dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_start_out : STD_LOGIC;
    signal dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_start_write : STD_LOGIC;
    signal dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_layer5_out_read : STD_LOGIC;
    signal dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_layer7_out_din : STD_LOGIC_VECTOR (15 downto 0);
    signal dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_layer7_out_write : STD_LOGIC;
    signal dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_w7_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_w7_EN_A : STD_LOGIC;
    signal dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_w7_WEN_A : STD_LOGIC_VECTOR (1 downto 0);
    signal dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_w7_Din_A : STD_LOGIC_VECTOR (15 downto 0);
    signal dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_w7_Addr_B : STD_LOGIC_VECTOR (31 downto 0);
    signal dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_w7_EN_B : STD_LOGIC;
    signal dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_w7_WEN_B : STD_LOGIC_VECTOR (1 downto 0);
    signal dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_w7_Din_B : STD_LOGIC_VECTOR (15 downto 0);
    signal sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_start : STD_LOGIC;
    signal sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_done : STD_LOGIC;
    signal sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_continue : STD_LOGIC;
    signal sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_idle : STD_LOGIC;
    signal sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_ready : STD_LOGIC;
    signal sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_layer7_out_read : STD_LOGIC;
    signal sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_layer8_out_TDATA : STD_LOGIC_VECTOR (15 downto 0);
    signal sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_layer8_out_TVALID : STD_LOGIC;
    signal layer2_out_full_n : STD_LOGIC;
    signal layer2_out_dout : STD_LOGIC_VECTOR (319 downto 0);
    signal layer2_out_num_data_valid : STD_LOGIC_VECTOR (8 downto 0);
    signal layer2_out_fifo_cap : STD_LOGIC_VECTOR (8 downto 0);
    signal layer2_out_empty_n : STD_LOGIC;
    signal layer3_out_full_n : STD_LOGIC;
    signal layer3_out_dout : STD_LOGIC_VECTOR (319 downto 0);
    signal layer3_out_num_data_valid : STD_LOGIC_VECTOR (8 downto 0);
    signal layer3_out_fifo_cap : STD_LOGIC_VECTOR (8 downto 0);
    signal layer3_out_empty_n : STD_LOGIC;
    signal layer4_out_full_n : STD_LOGIC;
    signal layer4_out_dout : STD_LOGIC_VECTOR (159 downto 0);
    signal layer4_out_num_data_valid : STD_LOGIC_VECTOR (8 downto 0);
    signal layer4_out_fifo_cap : STD_LOGIC_VECTOR (8 downto 0);
    signal layer4_out_empty_n : STD_LOGIC;
    signal layer5_out_full_n : STD_LOGIC;
    signal layer5_out_dout : STD_LOGIC_VECTOR (159 downto 0);
    signal layer5_out_num_data_valid : STD_LOGIC_VECTOR (8 downto 0);
    signal layer5_out_fifo_cap : STD_LOGIC_VECTOR (8 downto 0);
    signal layer5_out_empty_n : STD_LOGIC;
    signal layer7_out_full_n : STD_LOGIC;
    signal layer7_out_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal layer7_out_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal layer7_out_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal layer7_out_empty_n : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal ap_sync_reg_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_ready : STD_LOGIC;
    signal start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_full_n : STD_LOGIC;
    signal start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_empty_n : STD_LOGIC;
    signal start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_full_n : STD_LOGIC;
    signal start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_empty_n : STD_LOGIC;
    signal start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_full_n : STD_LOGIC;
    signal start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_empty_n : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        input_1_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
        input_1_TVALID : IN STD_LOGIC;
        input_1_TREADY : OUT STD_LOGIC;
        layer2_out_din : OUT STD_LOGIC_VECTOR (319 downto 0);
        layer2_out_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
        layer2_out_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0);
        layer2_out_full_n : IN STD_LOGIC;
        layer2_out_write : OUT STD_LOGIC;
        w2_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        w2_EN_A : OUT STD_LOGIC;
        w2_WEN_A : OUT STD_LOGIC_VECTOR (1 downto 0);
        w2_Din_A : OUT STD_LOGIC_VECTOR (15 downto 0);
        w2_Dout_A : IN STD_LOGIC_VECTOR (15 downto 0);
        w2_Addr_B : OUT STD_LOGIC_VECTOR (31 downto 0);
        w2_EN_B : OUT STD_LOGIC;
        w2_WEN_B : OUT STD_LOGIC_VECTOR (1 downto 0);
        w2_Din_B : OUT STD_LOGIC_VECTOR (15 downto 0);
        w2_Dout_B : IN STD_LOGIC_VECTOR (15 downto 0);
        b2_0 : IN STD_LOGIC_VECTOR (15 downto 0);
        b2_1 : IN STD_LOGIC_VECTOR (15 downto 0);
        b2_2 : IN STD_LOGIC_VECTOR (15 downto 0);
        b2_3 : IN STD_LOGIC_VECTOR (15 downto 0);
        b2_4 : IN STD_LOGIC_VECTOR (15 downto 0);
        b2_5 : IN STD_LOGIC_VECTOR (15 downto 0);
        b2_6 : IN STD_LOGIC_VECTOR (15 downto 0);
        b2_7 : IN STD_LOGIC_VECTOR (15 downto 0);
        b2_8 : IN STD_LOGIC_VECTOR (15 downto 0);
        b2_9 : IN STD_LOGIC_VECTOR (15 downto 0);
        b2_10 : IN STD_LOGIC_VECTOR (15 downto 0);
        b2_11 : IN STD_LOGIC_VECTOR (15 downto 0);
        b2_12 : IN STD_LOGIC_VECTOR (15 downto 0);
        b2_13 : IN STD_LOGIC_VECTOR (15 downto 0);
        b2_14 : IN STD_LOGIC_VECTOR (15 downto 0);
        b2_15 : IN STD_LOGIC_VECTOR (15 downto 0);
        b2_16 : IN STD_LOGIC_VECTOR (15 downto 0);
        b2_17 : IN STD_LOGIC_VECTOR (15 downto 0);
        b2_18 : IN STD_LOGIC_VECTOR (15 downto 0);
        b2_19 : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component myproject_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        layer2_out_dout : IN STD_LOGIC_VECTOR (319 downto 0);
        layer2_out_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
        layer2_out_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0);
        layer2_out_empty_n : IN STD_LOGIC;
        layer2_out_read : OUT STD_LOGIC;
        layer3_out_din : OUT STD_LOGIC_VECTOR (319 downto 0);
        layer3_out_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
        layer3_out_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0);
        layer3_out_full_n : IN STD_LOGIC;
        layer3_out_write : OUT STD_LOGIC );
    end component;


    component myproject_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        layer3_out_dout : IN STD_LOGIC_VECTOR (319 downto 0);
        layer3_out_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
        layer3_out_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0);
        layer3_out_empty_n : IN STD_LOGIC;
        layer3_out_read : OUT STD_LOGIC;
        layer4_out_din : OUT STD_LOGIC_VECTOR (159 downto 0);
        layer4_out_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
        layer4_out_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0);
        layer4_out_full_n : IN STD_LOGIC;
        layer4_out_write : OUT STD_LOGIC;
        w4_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        w4_EN_A : OUT STD_LOGIC;
        w4_WEN_A : OUT STD_LOGIC_VECTOR (1 downto 0);
        w4_Din_A : OUT STD_LOGIC_VECTOR (15 downto 0);
        w4_Dout_A : IN STD_LOGIC_VECTOR (15 downto 0);
        w4_Addr_B : OUT STD_LOGIC_VECTOR (31 downto 0);
        w4_EN_B : OUT STD_LOGIC;
        w4_WEN_B : OUT STD_LOGIC_VECTOR (1 downto 0);
        w4_Din_B : OUT STD_LOGIC_VECTOR (15 downto 0);
        w4_Dout_B : IN STD_LOGIC_VECTOR (15 downto 0);
        b4_0 : IN STD_LOGIC_VECTOR (15 downto 0);
        b4_1 : IN STD_LOGIC_VECTOR (15 downto 0);
        b4_2 : IN STD_LOGIC_VECTOR (15 downto 0);
        b4_3 : IN STD_LOGIC_VECTOR (15 downto 0);
        b4_4 : IN STD_LOGIC_VECTOR (15 downto 0);
        b4_5 : IN STD_LOGIC_VECTOR (15 downto 0);
        b4_6 : IN STD_LOGIC_VECTOR (15 downto 0);
        b4_7 : IN STD_LOGIC_VECTOR (15 downto 0);
        b4_8 : IN STD_LOGIC_VECTOR (15 downto 0);
        b4_9 : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component myproject_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        layer4_out_dout : IN STD_LOGIC_VECTOR (159 downto 0);
        layer4_out_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
        layer4_out_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0);
        layer4_out_empty_n : IN STD_LOGIC;
        layer4_out_read : OUT STD_LOGIC;
        layer5_out_din : OUT STD_LOGIC_VECTOR (159 downto 0);
        layer5_out_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
        layer5_out_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0);
        layer5_out_full_n : IN STD_LOGIC;
        layer5_out_write : OUT STD_LOGIC );
    end component;


    component myproject_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        layer5_out_dout : IN STD_LOGIC_VECTOR (159 downto 0);
        layer5_out_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
        layer5_out_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0);
        layer5_out_empty_n : IN STD_LOGIC;
        layer5_out_read : OUT STD_LOGIC;
        layer7_out_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        layer7_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        layer7_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        layer7_out_full_n : IN STD_LOGIC;
        layer7_out_write : OUT STD_LOGIC;
        w7_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        w7_EN_A : OUT STD_LOGIC;
        w7_WEN_A : OUT STD_LOGIC_VECTOR (1 downto 0);
        w7_Din_A : OUT STD_LOGIC_VECTOR (15 downto 0);
        w7_Dout_A : IN STD_LOGIC_VECTOR (15 downto 0);
        w7_Addr_B : OUT STD_LOGIC_VECTOR (31 downto 0);
        w7_EN_B : OUT STD_LOGIC;
        w7_WEN_B : OUT STD_LOGIC_VECTOR (1 downto 0);
        w7_Din_B : OUT STD_LOGIC_VECTOR (15 downto 0);
        w7_Dout_B : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component myproject_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        layer7_out_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        layer7_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        layer7_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        layer7_out_empty_n : IN STD_LOGIC;
        layer7_out_read : OUT STD_LOGIC;
        layer8_out_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
        layer8_out_TVALID : OUT STD_LOGIC;
        layer8_out_TREADY : IN STD_LOGIC );
    end component;


    component myproject_fifo_w320_d247_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (319 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (319 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (8 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (8 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component myproject_fifo_w160_d238_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (159 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (159 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (8 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (8 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component myproject_fifo_w16_d1_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (15 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (15 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component myproject_start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component myproject_start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component myproject_start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0 : component myproject_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_start,
        start_full_n => start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_full_n,
        ap_done => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_done,
        ap_continue => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_continue,
        ap_idle => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_idle,
        ap_ready => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_ready,
        start_out => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_start_out,
        start_write => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_start_write,
        input_1_TDATA => input_1_TDATA,
        input_1_TVALID => input_1_TVALID,
        input_1_TREADY => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_input_1_TREADY,
        layer2_out_din => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_layer2_out_din,
        layer2_out_num_data_valid => layer2_out_num_data_valid,
        layer2_out_fifo_cap => layer2_out_fifo_cap,
        layer2_out_full_n => layer2_out_full_n,
        layer2_out_write => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_layer2_out_write,
        w2_Addr_A => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_w2_Addr_A,
        w2_EN_A => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_w2_EN_A,
        w2_WEN_A => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_w2_WEN_A,
        w2_Din_A => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_w2_Din_A,
        w2_Dout_A => w2_Dout_A,
        w2_Addr_B => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_w2_Addr_B,
        w2_EN_B => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_w2_EN_B,
        w2_WEN_B => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_w2_WEN_B,
        w2_Din_B => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_w2_Din_B,
        w2_Dout_B => w2_Dout_B,
        b2_0 => b2_0,
        b2_1 => b2_1,
        b2_2 => b2_2,
        b2_3 => b2_3,
        b2_4 => b2_4,
        b2_5 => b2_5,
        b2_6 => b2_6,
        b2_7 => b2_7,
        b2_8 => b2_8,
        b2_9 => b2_9,
        b2_10 => b2_10,
        b2_11 => b2_11,
        b2_12 => b2_12,
        b2_13 => b2_13,
        b2_14 => b2_14,
        b2_15 => b2_15,
        b2_16 => b2_16,
        b2_17 => b2_17,
        b2_18 => b2_18,
        b2_19 => b2_19);

    relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0 : component myproject_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_start,
        ap_done => relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_done,
        ap_continue => relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_continue,
        ap_idle => relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_idle,
        ap_ready => relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_ready,
        layer2_out_dout => layer2_out_dout,
        layer2_out_num_data_valid => layer2_out_num_data_valid,
        layer2_out_fifo_cap => layer2_out_fifo_cap,
        layer2_out_empty_n => layer2_out_empty_n,
        layer2_out_read => relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_layer2_out_read,
        layer3_out_din => relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_layer3_out_din,
        layer3_out_num_data_valid => layer3_out_num_data_valid,
        layer3_out_fifo_cap => layer3_out_fifo_cap,
        layer3_out_full_n => layer3_out_full_n,
        layer3_out_write => relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_layer3_out_write);

    conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0 : component myproject_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_start,
        start_full_n => start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_full_n,
        ap_done => conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_done,
        ap_continue => conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_continue,
        ap_idle => conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_idle,
        ap_ready => conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_ready,
        start_out => conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_start_out,
        start_write => conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_start_write,
        layer3_out_dout => layer3_out_dout,
        layer3_out_num_data_valid => layer3_out_num_data_valid,
        layer3_out_fifo_cap => layer3_out_fifo_cap,
        layer3_out_empty_n => layer3_out_empty_n,
        layer3_out_read => conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_layer3_out_read,
        layer4_out_din => conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_layer4_out_din,
        layer4_out_num_data_valid => layer4_out_num_data_valid,
        layer4_out_fifo_cap => layer4_out_fifo_cap,
        layer4_out_full_n => layer4_out_full_n,
        layer4_out_write => conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_layer4_out_write,
        w4_Addr_A => conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_w4_Addr_A,
        w4_EN_A => conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_w4_EN_A,
        w4_WEN_A => conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_w4_WEN_A,
        w4_Din_A => conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_w4_Din_A,
        w4_Dout_A => w4_Dout_A,
        w4_Addr_B => conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_w4_Addr_B,
        w4_EN_B => conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_w4_EN_B,
        w4_WEN_B => conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_w4_WEN_B,
        w4_Din_B => conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_w4_Din_B,
        w4_Dout_B => w4_Dout_B,
        b4_0 => b4_0,
        b4_1 => b4_1,
        b4_2 => b4_2,
        b4_3 => b4_3,
        b4_4 => b4_4,
        b4_5 => b4_5,
        b4_6 => b4_6,
        b4_7 => b4_7,
        b4_8 => b4_8,
        b4_9 => b4_9);

    relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0 : component myproject_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_start,
        ap_done => relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_done,
        ap_continue => relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_continue,
        ap_idle => relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_idle,
        ap_ready => relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_ready,
        layer4_out_dout => layer4_out_dout,
        layer4_out_num_data_valid => layer4_out_num_data_valid,
        layer4_out_fifo_cap => layer4_out_fifo_cap,
        layer4_out_empty_n => layer4_out_empty_n,
        layer4_out_read => relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_layer4_out_read,
        layer5_out_din => relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_layer5_out_din,
        layer5_out_num_data_valid => layer5_out_num_data_valid,
        layer5_out_fifo_cap => layer5_out_fifo_cap,
        layer5_out_full_n => layer5_out_full_n,
        layer5_out_write => relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_layer5_out_write);

    dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0 : component myproject_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_start,
        start_full_n => start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_full_n,
        ap_done => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_done,
        ap_continue => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_continue,
        ap_idle => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_idle,
        ap_ready => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_ready,
        start_out => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_start_out,
        start_write => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_start_write,
        layer5_out_dout => layer5_out_dout,
        layer5_out_num_data_valid => layer5_out_num_data_valid,
        layer5_out_fifo_cap => layer5_out_fifo_cap,
        layer5_out_empty_n => layer5_out_empty_n,
        layer5_out_read => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_layer5_out_read,
        layer7_out_din => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_layer7_out_din,
        layer7_out_num_data_valid => layer7_out_num_data_valid,
        layer7_out_fifo_cap => layer7_out_fifo_cap,
        layer7_out_full_n => layer7_out_full_n,
        layer7_out_write => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_layer7_out_write,
        w7_Addr_A => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_w7_Addr_A,
        w7_EN_A => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_w7_EN_A,
        w7_WEN_A => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_w7_WEN_A,
        w7_Din_A => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_w7_Din_A,
        w7_Dout_A => w7_Dout_A,
        w7_Addr_B => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_w7_Addr_B,
        w7_EN_B => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_w7_EN_B,
        w7_WEN_B => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_w7_WEN_B,
        w7_Din_B => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_w7_Din_B,
        w7_Dout_B => w7_Dout_B);

    sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0 : component myproject_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_start,
        ap_done => sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_done,
        ap_continue => sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_continue,
        ap_idle => sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_idle,
        ap_ready => sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_ready,
        layer7_out_dout => layer7_out_dout,
        layer7_out_num_data_valid => layer7_out_num_data_valid,
        layer7_out_fifo_cap => layer7_out_fifo_cap,
        layer7_out_empty_n => layer7_out_empty_n,
        layer7_out_read => sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_layer7_out_read,
        layer8_out_TDATA => sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_layer8_out_TDATA,
        layer8_out_TVALID => sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_layer8_out_TVALID,
        layer8_out_TREADY => layer8_out_TREADY);

    layer2_out_U : component myproject_fifo_w320_d247_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_layer2_out_din,
        if_full_n => layer2_out_full_n,
        if_write => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_layer2_out_write,
        if_dout => layer2_out_dout,
        if_num_data_valid => layer2_out_num_data_valid,
        if_fifo_cap => layer2_out_fifo_cap,
        if_empty_n => layer2_out_empty_n,
        if_read => relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_layer2_out_read);

    layer3_out_U : component myproject_fifo_w320_d247_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_layer3_out_din,
        if_full_n => layer3_out_full_n,
        if_write => relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_layer3_out_write,
        if_dout => layer3_out_dout,
        if_num_data_valid => layer3_out_num_data_valid,
        if_fifo_cap => layer3_out_fifo_cap,
        if_empty_n => layer3_out_empty_n,
        if_read => conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_layer3_out_read);

    layer4_out_U : component myproject_fifo_w160_d238_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_layer4_out_din,
        if_full_n => layer4_out_full_n,
        if_write => conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_layer4_out_write,
        if_dout => layer4_out_dout,
        if_num_data_valid => layer4_out_num_data_valid,
        if_fifo_cap => layer4_out_fifo_cap,
        if_empty_n => layer4_out_empty_n,
        if_read => relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_layer4_out_read);

    layer5_out_U : component myproject_fifo_w160_d238_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_layer5_out_din,
        if_full_n => layer5_out_full_n,
        if_write => relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_layer5_out_write,
        if_dout => layer5_out_dout,
        if_num_data_valid => layer5_out_num_data_valid,
        if_fifo_cap => layer5_out_fifo_cap,
        if_empty_n => layer5_out_empty_n,
        if_read => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_layer5_out_read);

    layer7_out_U : component myproject_fifo_w16_d1_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_layer7_out_din,
        if_full_n => layer7_out_full_n,
        if_write => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_layer7_out_write,
        if_dout => layer7_out_dout,
        if_num_data_valid => layer7_out_num_data_valid,
        if_fifo_cap => layer7_out_fifo_cap,
        if_empty_n => layer7_out_empty_n,
        if_read => sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_layer7_out_read);

    start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_U : component myproject_start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_din,
        if_full_n => start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_full_n,
        if_write => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_start_write,
        if_dout => start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_dout,
        if_empty_n => start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_empty_n,
        if_read => relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_ready);

    start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_U : component myproject_start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_din,
        if_full_n => start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_full_n,
        if_write => conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_start_write,
        if_dout => start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_dout,
        if_empty_n => start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_empty_n,
        if_read => relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_ready);

    start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_U : component myproject_start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_din,
        if_full_n => start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_full_n,
        if_write => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_start_write,
        if_dout => start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_dout,
        if_empty_n => start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_empty_n,
        if_read => sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_ready);





    ap_sync_reg_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_ready <= ap_sync_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_ready <= ap_sync_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_ready <= ap_sync_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;

    ap_done <= sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_done;
    ap_idle <= (sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_idle and relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_idle and relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_idle and dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_idle and conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_idle and conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_idle);
    ap_ready <= ap_sync_ready;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sync_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_ready <= (conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_ready or ap_sync_reg_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_ready);
    ap_sync_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_ready <= (conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_ready or ap_sync_reg_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_ready);
    ap_sync_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_ready <= (dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_ready or ap_sync_reg_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_ready);
    ap_sync_ready <= (ap_sync_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_ready and ap_sync_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_ready and ap_sync_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_ready);
    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_continue <= ap_const_logic_1;
    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_start <= ((ap_sync_reg_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_ready xor ap_const_logic_1) and ap_start);
    conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_continue <= ap_const_logic_1;
    conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_start <= ((ap_sync_reg_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_ready xor ap_const_logic_1) and ap_start);
    dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_continue <= ap_const_logic_1;
    dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_start <= ((ap_sync_reg_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_ready xor ap_const_logic_1) and ap_start);
    input_1_TREADY <= conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_input_1_TREADY;
    layer8_out_TDATA <= sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_layer8_out_TDATA;
    layer8_out_TVALID <= sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_layer8_out_TVALID;
    relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_continue <= ap_const_logic_1;
    relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_start <= start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_empty_n;
    relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_continue <= ap_const_logic_1;
    relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_start <= start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_empty_n;
    sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_continue <= ap_const_logic_1;
    sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_start <= start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_empty_n;
    start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_din <= (0=>ap_const_logic_1, others=>'-');
    w2_Addr_A <= conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_w2_Addr_A;
    w2_Addr_B <= conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_w2_Addr_B;
    w2_Clk_A <= ap_clk;
    w2_Clk_B <= ap_clk;
    w2_Din_A <= ap_const_lv16_0;
    w2_Din_B <= ap_const_lv16_0;
    w2_EN_A <= conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_w2_EN_A;
    w2_EN_B <= conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_w2_EN_B;
    w2_Rst_A <= ap_rst_n_inv;
    w2_Rst_B <= ap_rst_n_inv;
    w2_WEN_A <= (0=>ap_const_logic_0, others=>'-');
    w2_WEN_B <= (0=>ap_const_logic_0, others=>'-');
    w4_Addr_A <= conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_w4_Addr_A;
    w4_Addr_B <= conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_w4_Addr_B;
    w4_Clk_A <= ap_clk;
    w4_Clk_B <= ap_clk;
    w4_Din_A <= ap_const_lv16_0;
    w4_Din_B <= ap_const_lv16_0;
    w4_EN_A <= conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_w4_EN_A;
    w4_EN_B <= conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_w4_EN_B;
    w4_Rst_A <= ap_rst_n_inv;
    w4_Rst_B <= ap_rst_n_inv;
    w4_WEN_A <= (0=>ap_const_logic_0, others=>'-');
    w4_WEN_B <= (0=>ap_const_logic_0, others=>'-');
    w7_Addr_A <= dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_w7_Addr_A;
    w7_Addr_B <= dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_w7_Addr_B;
    w7_Clk_A <= ap_clk;
    w7_Clk_B <= ap_clk;
    w7_Din_A <= ap_const_lv16_0;
    w7_Din_B <= ap_const_lv16_0;
    w7_EN_A <= dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_w7_EN_A;
    w7_EN_B <= dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_w7_EN_B;
    w7_Rst_A <= ap_rst_n_inv;
    w7_Rst_B <= ap_rst_n_inv;
    w7_WEN_A <= (0=>ap_const_logic_0, others=>'-');
    w7_WEN_B <= (0=>ap_const_logic_0, others=>'-');
end behav;
