// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="myproject_myproject,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcku5p-ffvb676-2-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=4.304000,HLS_SYN_LAT=416350,HLS_SYN_TPT=141314,HLS_SYN_MEM=55,HLS_SYN_DSP=0,HLS_SYN_FF=125441,HLS_SYN_LUT=141551,HLS_VERSION=2023_2}" *)

module myproject (
        input_1_TDATA,
        layer8_out_TDATA,
        w2_Addr_A,
        w2_EN_A,
        w2_Din_A,
        w2_Dout_A,
        w2_WEN_A,
        w2_Clk_A,
        ap_clk,
        w2_Rst_A,
        ap_rst_n,
        w2_Addr_B,
        w2_EN_B,
        w2_Din_B,
        w2_Dout_B,
        w2_WEN_B,
        w2_Clk_B,
        w2_Rst_B,
        b2_0,
        b2_1,
        b2_2,
        b2_3,
        b2_4,
        b2_5,
        b2_6,
        b2_7,
        b2_8,
        b2_9,
        b2_10,
        b2_11,
        b2_12,
        b2_13,
        b2_14,
        b2_15,
        b2_16,
        b2_17,
        b2_18,
        b2_19,
        w4_Addr_A,
        w4_EN_A,
        w4_Din_A,
        w4_Dout_A,
        w4_WEN_A,
        w4_Clk_A,
        w4_Rst_A,
        w4_Addr_B,
        w4_EN_B,
        w4_Din_B,
        w4_Dout_B,
        w4_WEN_B,
        w4_Clk_B,
        w4_Rst_B,
        b4_0,
        b4_1,
        b4_2,
        b4_3,
        b4_4,
        b4_5,
        b4_6,
        b4_7,
        b4_8,
        b4_9,
        w7_Addr_A,
        w7_EN_A,
        w7_Din_A,
        w7_Dout_A,
        w7_WEN_A,
        w7_Clk_A,
        w7_Rst_A,
        w7_Addr_B,
        w7_EN_B,
        w7_Din_B,
        w7_Dout_B,
        w7_WEN_B,
        w7_Clk_B,
        w7_Rst_B,
        input_1_TVALID,
        input_1_TREADY,
        ap_start,
        layer8_out_TVALID,
        layer8_out_TREADY,
        ap_done,
        ap_ready,
        ap_idle
);


input  [15:0] input_1_TDATA;
output  [15:0] layer8_out_TDATA;
output  [31:0] w2_Addr_A;
output   w2_EN_A;
output  [15:0] w2_Din_A;
input  [15:0] w2_Dout_A;
output  [1:0] w2_WEN_A;
output   w2_Clk_A;
input   ap_clk;
output   w2_Rst_A;
input   ap_rst_n;
output  [31:0] w2_Addr_B;
output   w2_EN_B;
output  [15:0] w2_Din_B;
input  [15:0] w2_Dout_B;
output  [1:0] w2_WEN_B;
output   w2_Clk_B;
output   w2_Rst_B;
input  [15:0] b2_0;
input  [15:0] b2_1;
input  [15:0] b2_2;
input  [15:0] b2_3;
input  [15:0] b2_4;
input  [15:0] b2_5;
input  [15:0] b2_6;
input  [15:0] b2_7;
input  [15:0] b2_8;
input  [15:0] b2_9;
input  [15:0] b2_10;
input  [15:0] b2_11;
input  [15:0] b2_12;
input  [15:0] b2_13;
input  [15:0] b2_14;
input  [15:0] b2_15;
input  [15:0] b2_16;
input  [15:0] b2_17;
input  [15:0] b2_18;
input  [15:0] b2_19;
output  [31:0] w4_Addr_A;
output   w4_EN_A;
output  [15:0] w4_Din_A;
input  [15:0] w4_Dout_A;
output  [1:0] w4_WEN_A;
output   w4_Clk_A;
output   w4_Rst_A;
output  [31:0] w4_Addr_B;
output   w4_EN_B;
output  [15:0] w4_Din_B;
input  [15:0] w4_Dout_B;
output  [1:0] w4_WEN_B;
output   w4_Clk_B;
output   w4_Rst_B;
input  [15:0] b4_0;
input  [15:0] b4_1;
input  [15:0] b4_2;
input  [15:0] b4_3;
input  [15:0] b4_4;
input  [15:0] b4_5;
input  [15:0] b4_6;
input  [15:0] b4_7;
input  [15:0] b4_8;
input  [15:0] b4_9;
output  [31:0] w7_Addr_A;
output   w7_EN_A;
output  [15:0] w7_Din_A;
input  [15:0] w7_Dout_A;
output  [1:0] w7_WEN_A;
output   w7_Clk_A;
output   w7_Rst_A;
output  [31:0] w7_Addr_B;
output   w7_EN_B;
output  [15:0] w7_Din_B;
input  [15:0] w7_Dout_B;
output  [1:0] w7_WEN_B;
output   w7_Clk_B;
output   w7_Rst_B;
input   input_1_TVALID;
output   input_1_TREADY;
input   ap_start;
output   layer8_out_TVALID;
input   layer8_out_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;

 reg    ap_rst_n_inv;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_start;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_done;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_continue;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_idle;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_ready;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_start_out;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_start_write;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_input_1_TREADY;
wire   [319:0] conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_layer2_out_din;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_layer2_out_write;
wire   [31:0] conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_w2_Addr_A;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_w2_EN_A;
wire   [1:0] conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_w2_WEN_A;
wire   [15:0] conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_w2_Din_A;
wire   [31:0] conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_w2_Addr_B;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_w2_EN_B;
wire   [1:0] conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_w2_WEN_B;
wire   [15:0] conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_w2_Din_B;
wire    relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_start;
wire    relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_done;
wire    relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_continue;
wire    relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_idle;
wire    relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_ready;
wire    relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_layer2_out_read;
wire   [319:0] relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_layer3_out_din;
wire    relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_layer3_out_write;
wire    conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_start;
wire    conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_done;
wire    conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_continue;
wire    conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_idle;
wire    conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_ready;
wire    conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_start_out;
wire    conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_start_write;
wire    conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_layer3_out_read;
wire   [159:0] conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_layer4_out_din;
wire    conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_layer4_out_write;
wire   [31:0] conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_w4_Addr_A;
wire    conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_w4_EN_A;
wire   [1:0] conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_w4_WEN_A;
wire   [15:0] conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_w4_Din_A;
wire   [31:0] conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_w4_Addr_B;
wire    conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_w4_EN_B;
wire   [1:0] conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_w4_WEN_B;
wire   [15:0] conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_w4_Din_B;
wire    relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_start;
wire    relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_done;
wire    relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_continue;
wire    relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_idle;
wire    relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_ready;
wire    relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_layer4_out_read;
wire   [159:0] relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_layer5_out_din;
wire    relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_layer5_out_write;
wire    dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_start;
wire    dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_done;
wire    dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_continue;
wire    dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_idle;
wire    dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_ready;
wire    dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_start_out;
wire    dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_start_write;
wire    dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_layer5_out_read;
wire   [15:0] dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_layer7_out_din;
wire    dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_layer7_out_write;
wire   [31:0] dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_w7_Addr_A;
wire    dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_w7_EN_A;
wire   [1:0] dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_w7_WEN_A;
wire   [15:0] dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_w7_Din_A;
wire   [31:0] dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_w7_Addr_B;
wire    dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_w7_EN_B;
wire   [1:0] dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_w7_WEN_B;
wire   [15:0] dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_w7_Din_B;
wire    sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_start;
wire    sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_done;
wire    sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_continue;
wire    sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_idle;
wire    sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_ready;
wire    sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_layer7_out_read;
wire   [15:0] sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_layer8_out_TDATA;
wire    sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_layer8_out_TVALID;
wire    layer2_out_full_n;
wire   [319:0] layer2_out_dout;
wire   [8:0] layer2_out_num_data_valid;
wire   [8:0] layer2_out_fifo_cap;
wire    layer2_out_empty_n;
wire    layer3_out_full_n;
wire   [319:0] layer3_out_dout;
wire   [8:0] layer3_out_num_data_valid;
wire   [8:0] layer3_out_fifo_cap;
wire    layer3_out_empty_n;
wire    layer4_out_full_n;
wire   [159:0] layer4_out_dout;
wire   [8:0] layer4_out_num_data_valid;
wire   [8:0] layer4_out_fifo_cap;
wire    layer4_out_empty_n;
wire    layer5_out_full_n;
wire   [159:0] layer5_out_dout;
wire   [8:0] layer5_out_num_data_valid;
wire   [8:0] layer5_out_fifo_cap;
wire    layer5_out_empty_n;
wire    layer7_out_full_n;
wire   [15:0] layer7_out_dout;
wire   [1:0] layer7_out_num_data_valid;
wire   [1:0] layer7_out_fifo_cap;
wire    layer7_out_empty_n;
wire    ap_sync_ready;
reg    ap_sync_reg_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_ready;
wire    ap_sync_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_ready;
reg    ap_sync_reg_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_ready;
wire    ap_sync_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_ready;
reg    ap_sync_reg_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_ready;
wire    ap_sync_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_ready;
wire   [0:0] start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_din;
wire    start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_full_n;
wire   [0:0] start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_dout;
wire    start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_empty_n;
wire   [0:0] start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_din;
wire    start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_full_n;
wire   [0:0] start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_dout;
wire    start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_empty_n;
wire   [0:0] start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_din;
wire    start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_full_n;
wire   [0:0] start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_dout;
wire    start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_ready = 1'b0;
#0 ap_sync_reg_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_ready = 1'b0;
#0 ap_sync_reg_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_ready = 1'b0;
end

myproject_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_s conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_start),
    .start_full_n(start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_full_n),
    .ap_done(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_done),
    .ap_continue(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_continue),
    .ap_idle(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_idle),
    .ap_ready(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_ready),
    .start_out(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_start_out),
    .start_write(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_start_write),
    .input_1_TDATA(input_1_TDATA),
    .input_1_TVALID(input_1_TVALID),
    .input_1_TREADY(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_input_1_TREADY),
    .layer2_out_din(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_layer2_out_din),
    .layer2_out_num_data_valid(layer2_out_num_data_valid),
    .layer2_out_fifo_cap(layer2_out_fifo_cap),
    .layer2_out_full_n(layer2_out_full_n),
    .layer2_out_write(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_layer2_out_write),
    .w2_Addr_A(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_w2_Addr_A),
    .w2_EN_A(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_w2_EN_A),
    .w2_WEN_A(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_w2_WEN_A),
    .w2_Din_A(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_w2_Din_A),
    .w2_Dout_A(w2_Dout_A),
    .w2_Addr_B(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_w2_Addr_B),
    .w2_EN_B(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_w2_EN_B),
    .w2_WEN_B(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_w2_WEN_B),
    .w2_Din_B(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_w2_Din_B),
    .w2_Dout_B(w2_Dout_B),
    .b2_0(b2_0),
    .b2_1(b2_1),
    .b2_2(b2_2),
    .b2_3(b2_3),
    .b2_4(b2_4),
    .b2_5(b2_5),
    .b2_6(b2_6),
    .b2_7(b2_7),
    .b2_8(b2_8),
    .b2_9(b2_9),
    .b2_10(b2_10),
    .b2_11(b2_11),
    .b2_12(b2_12),
    .b2_13(b2_13),
    .b2_14(b2_14),
    .b2_15(b2_15),
    .b2_16(b2_16),
    .b2_17(b2_17),
    .b2_18(b2_18),
    .b2_19(b2_19)
);

myproject_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_s relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_start),
    .ap_done(relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_done),
    .ap_continue(relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_continue),
    .ap_idle(relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_idle),
    .ap_ready(relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_ready),
    .layer2_out_dout(layer2_out_dout),
    .layer2_out_num_data_valid(layer2_out_num_data_valid),
    .layer2_out_fifo_cap(layer2_out_fifo_cap),
    .layer2_out_empty_n(layer2_out_empty_n),
    .layer2_out_read(relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_layer2_out_read),
    .layer3_out_din(relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_layer3_out_din),
    .layer3_out_num_data_valid(layer3_out_num_data_valid),
    .layer3_out_fifo_cap(layer3_out_fifo_cap),
    .layer3_out_full_n(layer3_out_full_n),
    .layer3_out_write(relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_layer3_out_write)
);

myproject_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_s conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_start),
    .start_full_n(start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_full_n),
    .ap_done(conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_done),
    .ap_continue(conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_continue),
    .ap_idle(conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_idle),
    .ap_ready(conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_ready),
    .start_out(conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_start_out),
    .start_write(conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_start_write),
    .layer3_out_dout(layer3_out_dout),
    .layer3_out_num_data_valid(layer3_out_num_data_valid),
    .layer3_out_fifo_cap(layer3_out_fifo_cap),
    .layer3_out_empty_n(layer3_out_empty_n),
    .layer3_out_read(conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_layer3_out_read),
    .layer4_out_din(conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_layer4_out_din),
    .layer4_out_num_data_valid(layer4_out_num_data_valid),
    .layer4_out_fifo_cap(layer4_out_fifo_cap),
    .layer4_out_full_n(layer4_out_full_n),
    .layer4_out_write(conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_layer4_out_write),
    .w4_Addr_A(conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_w4_Addr_A),
    .w4_EN_A(conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_w4_EN_A),
    .w4_WEN_A(conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_w4_WEN_A),
    .w4_Din_A(conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_w4_Din_A),
    .w4_Dout_A(w4_Dout_A),
    .w4_Addr_B(conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_w4_Addr_B),
    .w4_EN_B(conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_w4_EN_B),
    .w4_WEN_B(conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_w4_WEN_B),
    .w4_Din_B(conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_w4_Din_B),
    .w4_Dout_B(w4_Dout_B),
    .b4_0(b4_0),
    .b4_1(b4_1),
    .b4_2(b4_2),
    .b4_3(b4_3),
    .b4_4(b4_4),
    .b4_5(b4_5),
    .b4_6(b4_6),
    .b4_7(b4_7),
    .b4_8(b4_8),
    .b4_9(b4_9)
);

myproject_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_s relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_start),
    .ap_done(relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_done),
    .ap_continue(relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_continue),
    .ap_idle(relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_idle),
    .ap_ready(relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_ready),
    .layer4_out_dout(layer4_out_dout),
    .layer4_out_num_data_valid(layer4_out_num_data_valid),
    .layer4_out_fifo_cap(layer4_out_fifo_cap),
    .layer4_out_empty_n(layer4_out_empty_n),
    .layer4_out_read(relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_layer4_out_read),
    .layer5_out_din(relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_layer5_out_din),
    .layer5_out_num_data_valid(layer5_out_num_data_valid),
    .layer5_out_fifo_cap(layer5_out_fifo_cap),
    .layer5_out_full_n(layer5_out_full_n),
    .layer5_out_write(relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_layer5_out_write)
);

myproject_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_s dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_start),
    .start_full_n(start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_full_n),
    .ap_done(dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_done),
    .ap_continue(dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_continue),
    .ap_idle(dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_idle),
    .ap_ready(dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_ready),
    .start_out(dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_start_out),
    .start_write(dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_start_write),
    .layer5_out_dout(layer5_out_dout),
    .layer5_out_num_data_valid(layer5_out_num_data_valid),
    .layer5_out_fifo_cap(layer5_out_fifo_cap),
    .layer5_out_empty_n(layer5_out_empty_n),
    .layer5_out_read(dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_layer5_out_read),
    .layer7_out_din(dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_layer7_out_din),
    .layer7_out_num_data_valid(layer7_out_num_data_valid),
    .layer7_out_fifo_cap(layer7_out_fifo_cap),
    .layer7_out_full_n(layer7_out_full_n),
    .layer7_out_write(dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_layer7_out_write),
    .w7_Addr_A(dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_w7_Addr_A),
    .w7_EN_A(dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_w7_EN_A),
    .w7_WEN_A(dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_w7_WEN_A),
    .w7_Din_A(dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_w7_Din_A),
    .w7_Dout_A(w7_Dout_A),
    .w7_Addr_B(dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_w7_Addr_B),
    .w7_EN_B(dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_w7_EN_B),
    .w7_WEN_B(dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_w7_WEN_B),
    .w7_Din_B(dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_w7_Din_B),
    .w7_Dout_B(w7_Dout_B)
);

myproject_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_s sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_start),
    .ap_done(sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_done),
    .ap_continue(sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_continue),
    .ap_idle(sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_idle),
    .ap_ready(sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_ready),
    .layer7_out_dout(layer7_out_dout),
    .layer7_out_num_data_valid(layer7_out_num_data_valid),
    .layer7_out_fifo_cap(layer7_out_fifo_cap),
    .layer7_out_empty_n(layer7_out_empty_n),
    .layer7_out_read(sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_layer7_out_read),
    .layer8_out_TDATA(sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_layer8_out_TDATA),
    .layer8_out_TVALID(sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_layer8_out_TVALID),
    .layer8_out_TREADY(layer8_out_TREADY)
);

myproject_fifo_w320_d247_A layer2_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_layer2_out_din),
    .if_full_n(layer2_out_full_n),
    .if_write(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_layer2_out_write),
    .if_dout(layer2_out_dout),
    .if_num_data_valid(layer2_out_num_data_valid),
    .if_fifo_cap(layer2_out_fifo_cap),
    .if_empty_n(layer2_out_empty_n),
    .if_read(relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_layer2_out_read)
);

myproject_fifo_w320_d247_A layer3_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_layer3_out_din),
    .if_full_n(layer3_out_full_n),
    .if_write(relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_layer3_out_write),
    .if_dout(layer3_out_dout),
    .if_num_data_valid(layer3_out_num_data_valid),
    .if_fifo_cap(layer3_out_fifo_cap),
    .if_empty_n(layer3_out_empty_n),
    .if_read(conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_layer3_out_read)
);

myproject_fifo_w160_d238_A layer4_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_layer4_out_din),
    .if_full_n(layer4_out_full_n),
    .if_write(conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_layer4_out_write),
    .if_dout(layer4_out_dout),
    .if_num_data_valid(layer4_out_num_data_valid),
    .if_fifo_cap(layer4_out_fifo_cap),
    .if_empty_n(layer4_out_empty_n),
    .if_read(relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_layer4_out_read)
);

myproject_fifo_w160_d238_A layer5_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_layer5_out_din),
    .if_full_n(layer5_out_full_n),
    .if_write(relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_layer5_out_write),
    .if_dout(layer5_out_dout),
    .if_num_data_valid(layer5_out_num_data_valid),
    .if_fifo_cap(layer5_out_fifo_cap),
    .if_empty_n(layer5_out_empty_n),
    .if_read(dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_layer5_out_read)
);

myproject_fifo_w16_d1_S layer7_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_layer7_out_din),
    .if_full_n(layer7_out_full_n),
    .if_write(dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_layer7_out_write),
    .if_dout(layer7_out_dout),
    .if_num_data_valid(layer7_out_num_data_valid),
    .if_fifo_cap(layer7_out_fifo_cap),
    .if_empty_n(layer7_out_empty_n),
    .if_read(sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_layer7_out_read)
);

myproject_start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0 start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_din),
    .if_full_n(start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_full_n),
    .if_write(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_start_write),
    .if_dout(start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_dout),
    .if_empty_n(start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_empty_n),
    .if_read(relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_ready)
);

myproject_start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0 start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_din),
    .if_full_n(start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_full_n),
    .if_write(conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_start_write),
    .if_dout(start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_dout),
    .if_empty_n(start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_empty_n),
    .if_read(relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_ready)
);

myproject_start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0 start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_din),
    .if_full_n(start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_full_n),
    .if_write(dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_start_write),
    .if_dout(start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_dout),
    .if_empty_n(start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_empty_n),
    .if_read(sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_ready <= ap_sync_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_ready <= ap_sync_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_ready <= ap_sync_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_ready;
        end
    end
end

assign ap_done = sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_done;

assign ap_idle = (sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_idle & relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_idle & relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_idle & dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_idle & conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_idle & conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_idle);

assign ap_ready = ap_sync_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_ready = (conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_ready | ap_sync_reg_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_ready);

assign ap_sync_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_ready = (conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_ready | ap_sync_reg_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_ready);

assign ap_sync_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_ready = (dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_ready | ap_sync_reg_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_ready);

assign ap_sync_ready = (ap_sync_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_ready & ap_sync_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_ready & ap_sync_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_ready);

assign conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_continue = 1'b1;

assign conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_start = ((ap_sync_reg_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_ready ^ 1'b1) & ap_start);

assign conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_continue = 1'b1;

assign conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_start = ((ap_sync_reg_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_ready ^ 1'b1) & ap_start);

assign dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_continue = 1'b1;

assign dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_start = ((ap_sync_reg_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_ready ^ 1'b1) & ap_start);

assign input_1_TREADY = conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_input_1_TREADY;

assign layer8_out_TDATA = sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_layer8_out_TDATA;

assign layer8_out_TVALID = sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_layer8_out_TVALID;

assign relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_continue = 1'b1;

assign relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_start = start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_empty_n;

assign relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_continue = 1'b1;

assign relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_start = start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_empty_n;

assign sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_continue = 1'b1;

assign sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_start = start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_empty_n;

assign start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_din = 1'b1;

assign start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_din = 1'b1;

assign start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_din = 1'b1;

assign w2_Addr_A = conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_w2_Addr_A;

assign w2_Addr_B = conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_w2_Addr_B;

assign w2_Clk_A = ap_clk;

assign w2_Clk_B = ap_clk;

assign w2_Din_A = 16'd0;

assign w2_Din_B = 16'd0;

assign w2_EN_A = conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_w2_EN_A;

assign w2_EN_B = conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_w2_EN_B;

assign w2_Rst_A = ap_rst_n_inv;

assign w2_Rst_B = ap_rst_n_inv;

assign w2_WEN_A = 1'b0;

assign w2_WEN_B = 1'b0;

assign w4_Addr_A = conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_w4_Addr_A;

assign w4_Addr_B = conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_w4_Addr_B;

assign w4_Clk_A = ap_clk;

assign w4_Clk_B = ap_clk;

assign w4_Din_A = 16'd0;

assign w4_Din_B = 16'd0;

assign w4_EN_A = conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_w4_EN_A;

assign w4_EN_B = conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_w4_EN_B;

assign w4_Rst_A = ap_rst_n_inv;

assign w4_Rst_B = ap_rst_n_inv;

assign w4_WEN_A = 1'b0;

assign w4_WEN_B = 1'b0;

assign w7_Addr_A = dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_w7_Addr_A;

assign w7_Addr_B = dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_w7_Addr_B;

assign w7_Clk_A = ap_clk;

assign w7_Clk_B = ap_clk;

assign w7_Din_A = 16'd0;

assign w7_Din_B = 16'd0;

assign w7_EN_A = dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_w7_EN_A;

assign w7_EN_B = dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_w7_EN_B;

assign w7_Rst_A = ap_rst_n_inv;

assign w7_Rst_B = ap_rst_n_inv;

assign w7_WEN_A = 1'b0;

assign w7_WEN_B = 1'b0;


reg find_df_deadlock = 0;
// synthesis translate_off
`include "myproject_hls_deadlock_detector.vh"
// synthesis translate_on

reg find_kernel_block = 0;
// synthesis translate_off
`include "myproject_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //myproject

