-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject is
generic (
    C_S_AXI_CTRL_ADDR_WIDTH : INTEGER := 4;
    C_S_AXI_CTRL_DATA_WIDTH : INTEGER := 32 );
port (
    s_axi_CTRL_AWVALID : IN STD_LOGIC;
    s_axi_CTRL_AWREADY : OUT STD_LOGIC;
    s_axi_CTRL_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_WVALID : IN STD_LOGIC;
    s_axi_CTRL_WREADY : OUT STD_LOGIC;
    s_axi_CTRL_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH/8-1 downto 0);
    s_axi_CTRL_ARVALID : IN STD_LOGIC;
    s_axi_CTRL_ARREADY : OUT STD_LOGIC;
    s_axi_CTRL_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_RVALID : OUT STD_LOGIC;
    s_axi_CTRL_RREADY : IN STD_LOGIC;
    s_axi_CTRL_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CTRL_BVALID : OUT STD_LOGIC;
    s_axi_CTRL_BREADY : IN STD_LOGIC;
    s_axi_CTRL_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    interrupt : OUT STD_LOGIC;
    input_1_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    layer8_out_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_1_TVALID : IN STD_LOGIC;
    input_1_TREADY : OUT STD_LOGIC;
    layer8_out_TVALID : OUT STD_LOGIC;
    layer8_out_TREADY : IN STD_LOGIC );
end;


architecture behav of myproject is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "myproject_myproject,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcku5p-ffvb676-2-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=3.922500,HLS_SYN_LAT=4420,HLS_SYN_TPT=3953,HLS_SYN_MEM=55,HLS_SYN_DSP=0,HLS_SYN_FF=5055,HLS_SYN_LUT=4319,HLS_VERSION=2023_2}";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_ready : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_start : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_done : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_continue : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_idle : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_ready : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_start_out : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_start_write : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_input_1_TREADY : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_layer2_out_din : STD_LOGIC_VECTOR (319 downto 0);
    signal conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_layer2_out_write : STD_LOGIC;
    signal relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_start : STD_LOGIC;
    signal relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_done : STD_LOGIC;
    signal relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_continue : STD_LOGIC;
    signal relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_idle : STD_LOGIC;
    signal relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_ready : STD_LOGIC;
    signal relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_layer2_out_read : STD_LOGIC;
    signal relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_layer3_out_din : STD_LOGIC_VECTOR (319 downto 0);
    signal relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_layer3_out_write : STD_LOGIC;
    signal relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_start_out : STD_LOGIC;
    signal relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_start_write : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_start : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_done : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_continue : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_idle : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_ready : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_start_out : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_start_write : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_layer3_out_read : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_layer4_out_din : STD_LOGIC_VECTOR (159 downto 0);
    signal conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_layer4_out_write : STD_LOGIC;
    signal relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_start : STD_LOGIC;
    signal relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_done : STD_LOGIC;
    signal relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_continue : STD_LOGIC;
    signal relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_idle : STD_LOGIC;
    signal relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_ready : STD_LOGIC;
    signal relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_layer4_out_read : STD_LOGIC;
    signal relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_layer5_out_din : STD_LOGIC_VECTOR (159 downto 0);
    signal relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_layer5_out_write : STD_LOGIC;
    signal relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_start_out : STD_LOGIC;
    signal relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_start_write : STD_LOGIC;
    signal dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_start : STD_LOGIC;
    signal dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_done : STD_LOGIC;
    signal dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_continue : STD_LOGIC;
    signal dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_idle : STD_LOGIC;
    signal dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_ready : STD_LOGIC;
    signal dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_start_out : STD_LOGIC;
    signal dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_start_write : STD_LOGIC;
    signal dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_layer5_out_read : STD_LOGIC;
    signal dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_layer7_out_din : STD_LOGIC_VECTOR (15 downto 0);
    signal dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_layer7_out_write : STD_LOGIC;
    signal sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_start : STD_LOGIC;
    signal sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_done : STD_LOGIC;
    signal sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_continue : STD_LOGIC;
    signal sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_idle : STD_LOGIC;
    signal sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_ready : STD_LOGIC;
    signal sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_layer7_out_read : STD_LOGIC;
    signal sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_layer8_out_TDATA : STD_LOGIC_VECTOR (15 downto 0);
    signal sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_layer8_out_TVALID : STD_LOGIC;
    signal layer2_out_full_n : STD_LOGIC;
    signal layer2_out_dout : STD_LOGIC_VECTOR (319 downto 0);
    signal layer2_out_num_data_valid : STD_LOGIC_VECTOR (8 downto 0);
    signal layer2_out_fifo_cap : STD_LOGIC_VECTOR (8 downto 0);
    signal layer2_out_empty_n : STD_LOGIC;
    signal layer3_out_full_n : STD_LOGIC;
    signal layer3_out_dout : STD_LOGIC_VECTOR (319 downto 0);
    signal layer3_out_num_data_valid : STD_LOGIC_VECTOR (8 downto 0);
    signal layer3_out_fifo_cap : STD_LOGIC_VECTOR (8 downto 0);
    signal layer3_out_empty_n : STD_LOGIC;
    signal layer4_out_full_n : STD_LOGIC;
    signal layer4_out_dout : STD_LOGIC_VECTOR (159 downto 0);
    signal layer4_out_num_data_valid : STD_LOGIC_VECTOR (8 downto 0);
    signal layer4_out_fifo_cap : STD_LOGIC_VECTOR (8 downto 0);
    signal layer4_out_empty_n : STD_LOGIC;
    signal layer5_out_full_n : STD_LOGIC;
    signal layer5_out_dout : STD_LOGIC_VECTOR (159 downto 0);
    signal layer5_out_num_data_valid : STD_LOGIC_VECTOR (8 downto 0);
    signal layer5_out_fifo_cap : STD_LOGIC_VECTOR (8 downto 0);
    signal layer5_out_empty_n : STD_LOGIC;
    signal layer7_out_full_n : STD_LOGIC;
    signal layer7_out_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal layer7_out_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal layer7_out_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal layer7_out_empty_n : STD_LOGIC;
    signal start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_full_n : STD_LOGIC;
    signal start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_empty_n : STD_LOGIC;
    signal start_for_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_full_n : STD_LOGIC;
    signal start_for_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_empty_n : STD_LOGIC;
    signal start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_full_n : STD_LOGIC;
    signal start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_empty_n : STD_LOGIC;
    signal start_for_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_full_n : STD_LOGIC;
    signal start_for_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_empty_n : STD_LOGIC;
    signal start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_full_n : STD_LOGIC;
    signal start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_empty_n : STD_LOGIC;

    component myproject_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        input_1_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
        input_1_TVALID : IN STD_LOGIC;
        input_1_TREADY : OUT STD_LOGIC;
        layer2_out_din : OUT STD_LOGIC_VECTOR (319 downto 0);
        layer2_out_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
        layer2_out_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0);
        layer2_out_full_n : IN STD_LOGIC;
        layer2_out_write : OUT STD_LOGIC );
    end component;


    component myproject_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        layer2_out_dout : IN STD_LOGIC_VECTOR (319 downto 0);
        layer2_out_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
        layer2_out_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0);
        layer2_out_empty_n : IN STD_LOGIC;
        layer2_out_read : OUT STD_LOGIC;
        layer3_out_din : OUT STD_LOGIC_VECTOR (319 downto 0);
        layer3_out_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
        layer3_out_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0);
        layer3_out_full_n : IN STD_LOGIC;
        layer3_out_write : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC );
    end component;


    component myproject_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        layer3_out_dout : IN STD_LOGIC_VECTOR (319 downto 0);
        layer3_out_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
        layer3_out_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0);
        layer3_out_empty_n : IN STD_LOGIC;
        layer3_out_read : OUT STD_LOGIC;
        layer4_out_din : OUT STD_LOGIC_VECTOR (159 downto 0);
        layer4_out_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
        layer4_out_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0);
        layer4_out_full_n : IN STD_LOGIC;
        layer4_out_write : OUT STD_LOGIC );
    end component;


    component myproject_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        layer4_out_dout : IN STD_LOGIC_VECTOR (159 downto 0);
        layer4_out_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
        layer4_out_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0);
        layer4_out_empty_n : IN STD_LOGIC;
        layer4_out_read : OUT STD_LOGIC;
        layer5_out_din : OUT STD_LOGIC_VECTOR (159 downto 0);
        layer5_out_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
        layer5_out_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0);
        layer5_out_full_n : IN STD_LOGIC;
        layer5_out_write : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC );
    end component;


    component myproject_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        layer5_out_dout : IN STD_LOGIC_VECTOR (159 downto 0);
        layer5_out_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
        layer5_out_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0);
        layer5_out_empty_n : IN STD_LOGIC;
        layer5_out_read : OUT STD_LOGIC;
        layer7_out_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        layer7_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        layer7_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        layer7_out_full_n : IN STD_LOGIC;
        layer7_out_write : OUT STD_LOGIC );
    end component;


    component myproject_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        layer7_out_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        layer7_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        layer7_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        layer7_out_empty_n : IN STD_LOGIC;
        layer7_out_read : OUT STD_LOGIC;
        layer8_out_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
        layer8_out_TVALID : OUT STD_LOGIC;
        layer8_out_TREADY : IN STD_LOGIC );
    end component;


    component myproject_fifo_w320_d247_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (319 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (319 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (8 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (8 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component myproject_fifo_w160_d238_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (159 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (159 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (8 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (8 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component myproject_fifo_w16_d1_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (15 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (15 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component myproject_start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component myproject_start_for_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4fYi IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component myproject_start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component myproject_start_for_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component myproject_start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component myproject_CTRL_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;



begin
    CTRL_s_axi_U : component myproject_CTRL_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CTRL_AWVALID,
        AWREADY => s_axi_CTRL_AWREADY,
        AWADDR => s_axi_CTRL_AWADDR,
        WVALID => s_axi_CTRL_WVALID,
        WREADY => s_axi_CTRL_WREADY,
        WDATA => s_axi_CTRL_WDATA,
        WSTRB => s_axi_CTRL_WSTRB,
        ARVALID => s_axi_CTRL_ARVALID,
        ARREADY => s_axi_CTRL_ARREADY,
        ARADDR => s_axi_CTRL_ARADDR,
        RVALID => s_axi_CTRL_RVALID,
        RREADY => s_axi_CTRL_RREADY,
        RDATA => s_axi_CTRL_RDATA,
        RRESP => s_axi_CTRL_RRESP,
        BVALID => s_axi_CTRL_BVALID,
        BREADY => s_axi_CTRL_BREADY,
        BRESP => s_axi_CTRL_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0 : component myproject_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_start,
        start_full_n => start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_full_n,
        ap_done => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_done,
        ap_continue => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_continue,
        ap_idle => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_idle,
        ap_ready => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_ready,
        start_out => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_start_out,
        start_write => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_start_write,
        input_1_TDATA => input_1_TDATA,
        input_1_TVALID => input_1_TVALID,
        input_1_TREADY => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_input_1_TREADY,
        layer2_out_din => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_layer2_out_din,
        layer2_out_num_data_valid => layer2_out_num_data_valid,
        layer2_out_fifo_cap => layer2_out_fifo_cap,
        layer2_out_full_n => layer2_out_full_n,
        layer2_out_write => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_layer2_out_write);

    relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0 : component myproject_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_start,
        start_full_n => start_for_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_full_n,
        ap_done => relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_done,
        ap_continue => relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_continue,
        ap_idle => relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_idle,
        ap_ready => relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_ready,
        layer2_out_dout => layer2_out_dout,
        layer2_out_num_data_valid => layer2_out_num_data_valid,
        layer2_out_fifo_cap => layer2_out_fifo_cap,
        layer2_out_empty_n => layer2_out_empty_n,
        layer2_out_read => relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_layer2_out_read,
        layer3_out_din => relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_layer3_out_din,
        layer3_out_num_data_valid => layer3_out_num_data_valid,
        layer3_out_fifo_cap => layer3_out_fifo_cap,
        layer3_out_full_n => layer3_out_full_n,
        layer3_out_write => relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_layer3_out_write,
        start_out => relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_start_out,
        start_write => relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_start_write);

    conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0 : component myproject_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_start,
        start_full_n => start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_full_n,
        ap_done => conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_done,
        ap_continue => conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_continue,
        ap_idle => conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_idle,
        ap_ready => conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_ready,
        start_out => conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_start_out,
        start_write => conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_start_write,
        layer3_out_dout => layer3_out_dout,
        layer3_out_num_data_valid => layer3_out_num_data_valid,
        layer3_out_fifo_cap => layer3_out_fifo_cap,
        layer3_out_empty_n => layer3_out_empty_n,
        layer3_out_read => conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_layer3_out_read,
        layer4_out_din => conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_layer4_out_din,
        layer4_out_num_data_valid => layer4_out_num_data_valid,
        layer4_out_fifo_cap => layer4_out_fifo_cap,
        layer4_out_full_n => layer4_out_full_n,
        layer4_out_write => conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_layer4_out_write);

    relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0 : component myproject_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_start,
        start_full_n => start_for_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_full_n,
        ap_done => relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_done,
        ap_continue => relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_continue,
        ap_idle => relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_idle,
        ap_ready => relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_ready,
        layer4_out_dout => layer4_out_dout,
        layer4_out_num_data_valid => layer4_out_num_data_valid,
        layer4_out_fifo_cap => layer4_out_fifo_cap,
        layer4_out_empty_n => layer4_out_empty_n,
        layer4_out_read => relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_layer4_out_read,
        layer5_out_din => relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_layer5_out_din,
        layer5_out_num_data_valid => layer5_out_num_data_valid,
        layer5_out_fifo_cap => layer5_out_fifo_cap,
        layer5_out_full_n => layer5_out_full_n,
        layer5_out_write => relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_layer5_out_write,
        start_out => relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_start_out,
        start_write => relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_start_write);

    dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0 : component myproject_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_start,
        start_full_n => start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_full_n,
        ap_done => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_done,
        ap_continue => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_continue,
        ap_idle => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_idle,
        ap_ready => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_ready,
        start_out => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_start_out,
        start_write => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_start_write,
        layer5_out_dout => layer5_out_dout,
        layer5_out_num_data_valid => layer5_out_num_data_valid,
        layer5_out_fifo_cap => layer5_out_fifo_cap,
        layer5_out_empty_n => layer5_out_empty_n,
        layer5_out_read => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_layer5_out_read,
        layer7_out_din => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_layer7_out_din,
        layer7_out_num_data_valid => layer7_out_num_data_valid,
        layer7_out_fifo_cap => layer7_out_fifo_cap,
        layer7_out_full_n => layer7_out_full_n,
        layer7_out_write => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_layer7_out_write);

    sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0 : component myproject_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_start,
        ap_done => sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_done,
        ap_continue => sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_continue,
        ap_idle => sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_idle,
        ap_ready => sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_ready,
        layer7_out_dout => layer7_out_dout,
        layer7_out_num_data_valid => layer7_out_num_data_valid,
        layer7_out_fifo_cap => layer7_out_fifo_cap,
        layer7_out_empty_n => layer7_out_empty_n,
        layer7_out_read => sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_layer7_out_read,
        layer8_out_TDATA => sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_layer8_out_TDATA,
        layer8_out_TVALID => sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_layer8_out_TVALID,
        layer8_out_TREADY => layer8_out_TREADY);

    layer2_out_U : component myproject_fifo_w320_d247_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_layer2_out_din,
        if_full_n => layer2_out_full_n,
        if_write => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_layer2_out_write,
        if_dout => layer2_out_dout,
        if_num_data_valid => layer2_out_num_data_valid,
        if_fifo_cap => layer2_out_fifo_cap,
        if_empty_n => layer2_out_empty_n,
        if_read => relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_layer2_out_read);

    layer3_out_U : component myproject_fifo_w320_d247_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_layer3_out_din,
        if_full_n => layer3_out_full_n,
        if_write => relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_layer3_out_write,
        if_dout => layer3_out_dout,
        if_num_data_valid => layer3_out_num_data_valid,
        if_fifo_cap => layer3_out_fifo_cap,
        if_empty_n => layer3_out_empty_n,
        if_read => conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_layer3_out_read);

    layer4_out_U : component myproject_fifo_w160_d238_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_layer4_out_din,
        if_full_n => layer4_out_full_n,
        if_write => conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_layer4_out_write,
        if_dout => layer4_out_dout,
        if_num_data_valid => layer4_out_num_data_valid,
        if_fifo_cap => layer4_out_fifo_cap,
        if_empty_n => layer4_out_empty_n,
        if_read => relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_layer4_out_read);

    layer5_out_U : component myproject_fifo_w160_d238_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_layer5_out_din,
        if_full_n => layer5_out_full_n,
        if_write => relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_layer5_out_write,
        if_dout => layer5_out_dout,
        if_num_data_valid => layer5_out_num_data_valid,
        if_fifo_cap => layer5_out_fifo_cap,
        if_empty_n => layer5_out_empty_n,
        if_read => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_layer5_out_read);

    layer7_out_U : component myproject_fifo_w16_d1_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_layer7_out_din,
        if_full_n => layer7_out_full_n,
        if_write => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_layer7_out_write,
        if_dout => layer7_out_dout,
        if_num_data_valid => layer7_out_num_data_valid,
        if_fifo_cap => layer7_out_fifo_cap,
        if_empty_n => layer7_out_empty_n,
        if_read => sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_layer7_out_read);

    start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_U : component myproject_start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_din,
        if_full_n => start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_full_n,
        if_write => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_start_write,
        if_dout => start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_dout,
        if_empty_n => start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_empty_n,
        if_read => relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_ready);

    start_for_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4fYi_U : component myproject_start_for_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4fYi
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_din,
        if_full_n => start_for_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_full_n,
        if_write => relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_start_write,
        if_dout => start_for_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_dout,
        if_empty_n => start_for_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_empty_n,
        if_read => conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_ready);

    start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_U : component myproject_start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_din,
        if_full_n => start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_full_n,
        if_write => conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_start_write,
        if_dout => start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_dout,
        if_empty_n => start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_empty_n,
        if_read => relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_ready);

    start_for_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_U : component myproject_start_for_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_din,
        if_full_n => start_for_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_full_n,
        if_write => relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_start_write,
        if_dout => start_for_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_dout,
        if_empty_n => start_for_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_empty_n,
        if_read => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_ready);

    start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_U : component myproject_start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_din,
        if_full_n => start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_full_n,
        if_write => dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_start_write,
        if_dout => start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_dout,
        if_empty_n => start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_empty_n,
        if_read => sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_ready);




    ap_done <= sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_done;
    ap_idle <= (sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_idle and relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_idle and relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_idle and dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_idle and conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_idle and conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_idle);
    ap_ready <= conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_ready;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_continue <= ap_const_logic_1;
    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_ap_start <= ap_start;
    conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_continue <= ap_const_logic_1;
    conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_ap_start <= start_for_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_empty_n;
    dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_continue <= ap_const_logic_1;
    dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_ap_start <= start_for_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_empty_n;
    input_1_TREADY <= conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_20u_config2_U0_input_1_TREADY;
    layer8_out_TDATA <= sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_layer8_out_TDATA;
    layer8_out_TVALID <= sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_layer8_out_TVALID;
    relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_continue <= ap_const_logic_1;
    relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_ap_start <= start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_empty_n;
    relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_continue <= ap_const_logic_1;
    relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_ap_start <= start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_empty_n;
    sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_continue <= ap_const_logic_1;
    sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_ap_start <= start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_empty_n;
    start_for_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_10u_config4_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_dense_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_1u_config7_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config5_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_6_5_3_0_20u_relu_config3_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config8_U0_din <= (0=>ap_const_logic_1, others=>'-');
end behav;
